### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by joshmcintosh** [Ross-Alexandra/TheGame#22]
Steps to repro:

1. open the game

2. Click around a bunch

Intended Result:

1. The game continues running regardless of input

Actual Result:

1. The game freezes and produces the following error until it crashes

```ERROR:root:Exception caught in main loop: can't start new thread
Traceback (most recent call last):
  File "C:\Users\Josh\source\repos\Ross-Alexandra\TheGame\thegame\engine\engine.py", line 42, in start
    self._main_loop()
  File "C:\Users\Josh\source\repos\Ross-Alexandra\TheGame\thegame\engine\engine.py", line 93, in _main_loop
    self._schedule_events(events=events, number_of_events=number_of_events)
  File "C:\Users\Josh\source\repos\Ross-Alexandra\TheGame\thegame\engine\engine.py", line 170, in _schedule_events
    event_pool = ThreadPool(processes=number_of_events)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 789, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\dummy\__init__.py", line 48, in start
    threading.Thread.start(self)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
INFO:root:Pygame successfully uninitialized.
Traceback (most recent call last):
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Josh\source\repos\Ross-Alexandra\TheGame\thegame\__main__.py", line 51, in <module>
    start_game()
  File "C:\Users\Josh\source\repos\Ross-Alexandra\TheGame\thegame\__main__.py", line 43, in start_game
    game_engine.start()
  File "C:\Users\Josh\source\repos\Ross-Alexandra\TheGame\thegame\engine\engine.py", line 42, in start
    self._main_loop()
  File "C:\Users\Josh\source\repos\Ross-Alexandra\TheGame\thegame\engine\engine.py", line 93, in _main_loop
    self._schedule_events(events=events, number_of_events=number_of_events)
  File "C:\Users\Josh\source\repos\Ross-Alexandra\TheGame\thegame\engine\engine.py", line 170, in _schedule_events
    event_pool = ThreadPool(processes=number_of_events)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 789, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\dummy\__init__.py", line 48, in start
    threading.Thread.start(self)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread```

**Comment by Ross-Alexandra** [comment]
Upon further inspection it appears that this is caused by a thread pool being created every loop that events occur in. I can't personally recreate this issue, however I have created a potential fix in branch GH-22. Please check to see if this resolves your issues, and if so please approve the PR.

**Comment by joshmcintosh** [comment]
Bug could not be reproduced when using GH-22. Approving pull request #23
